version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - scbuildcodeunits
    aliases:
      - basebuildallcodeunits
      - bb

  GryvabitcoinnodeRunExample:
    desc: "GRYVABitcoinNode: Run example"
    silent: true
    dir: "."
    cmds:
      - python GRYVABitcoinNode/Other/Reference/ReferenceContent/Examples/MinimalDockerComposeFile/RunExample.py
    aliases:
      - gryvabitcoinnoderunexample
